backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Navigation Title", name: "navtitle", widget: "string" }
      - { label: "Strapline", name: "strapline", widget: "string" }
      - { label: "Story Strapline", name: "storyStrapline", widget: "string" }
      - { label: "Story Content", name: "storyContent", widget: "string" }
      - { label: "Banner Strapline", name: "bannerStrapline", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Telephone", name: "telephone", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Copyright", name: "copyright", widget: "string" }
